### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by VonYH** [sonvirgo/Hackintosh-i5-12400-iGPU-UHD730#1]
i have a computer with 13400. and it certainly uses uhd770. 
would you please tell me how does it work?
and maybe you can share the efi file with me

**Comment by sonvirgo** [comment]
it works as VESA mode, lag, for experimental only while waiting for supported VGA to arrive.
Further more I don't do any thing for free.
I do hackintosh service and charge small amount accordingly 
![image](https://github.com/sonvirgo/Hackintosh-i5-12400-iGPU-UHD730/assets/10823037/7099b77c-9dac-4b37-9e40-49fa303bd71b)
